# Generated by Django 3.1.2 on 2022-04-15 13:46

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefFiliere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeChefFiliere', models.CharField(error_messages={'unique': 'Code Chef de filière déjà existant !'}, max_length=200, unique=True, verbose_name='Code Chef de filière')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cheffiliere', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chefs de filières',
                'db_table': 'Chef de filière',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeEnseignant', models.CharField(error_messages={'unique': 'Code Enseignant déjà existant !'}, max_length=200, unique=True, verbose_name='Code Enseignant')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdn.cheffiliere', verbose_name='Chef de filière')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Enseignants',
                'db_table': 'Enseignant',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numapogee', models.CharField(error_messages={'unique': 'N° Apogée déjà existant !.'}, max_length=200, unique=True, verbose_name='N° Apogée')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdn.cheffiliere', verbose_name='Responsable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Étudiants',
                'db_table': 'Étudiant',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(error_messages={'unique': 'Matière déjà existante !'}, max_length=200, unique=True, verbose_name='Matière')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdn.enseignant', verbose_name='Instructeur')),
            ],
            options={
                'verbose_name_plural': 'Matières',
                'db_table': 'Matière',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name="Date d'examen")),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdn.etudiant', verbose_name='Étudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdn.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'db_table': 'Note',
            },
        ),
    ]
